/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.gauthamkrishna9991.j3toe;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Board boardunderTest = new Board();
        assertNotNull(boardunderTest);
    }
}
