/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.gauthamkrishna9991.j3toe;

public class App {

    public static void main(String[] args) {
        Board.playGame();
    }
}
